version: "3.7"
services:
    ### DATABASE ###
    db:
        image: postgres:14.1
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: postgres
            POSTGRES_DB: banco
            PGDATA: /data/postgres
        volumes:
          - database:/data/postgres
        networks:
            - backend


    ### BACKEND ###
    backend:
        build: ./backend
        container_name: nest_backend
        ports:
            - "3001:3001"
        depends_on:
            - db
        # restart: always
        environment:
          - TYPEORM_HOST=postgres
        volumes:
          - ./backend:/usr/src/devmenager/backend
        networks:
            - backend
            - frontend
        command: ["npm", "run", "start:dev"]

    ### FRONTEND ###
    frontend:
        build: ./frontend
        container_name: nextjs_front
        volumes:
          - ./frontend/src:/usr/src/devmenager/frontend/src
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - frontend
        # command: npm start
        command: ["npm", "run", "dev"]

networks:
    backend:

    frontend:

volumes:
    database:
