version: "3.7"
services:
    ### DATABASE ###
    db:
        image: postgres:14.1
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: postgres
            POSTGRES_DB: banco
        networks:
            - backend


    ### BACKEND ###
    backend:
        build: ./backend
        container_name: nest_backend
        ports:
            - "3001:3001"
        depends_on:
            - db
        restart: always
        volumes:
          - ./backend:/usr/backend
        networks:
            - backend
            - frontend
        command: npm run dev

    ### FRONTEND ###
    frontend:
        build: ./frontend
        container_name: nextjs_front
        volumes:
          - ./frontend:/usr/frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
        networks:
            - frontend
        command: npm start

networks:
    backend:

    frontend:
